booqable/horton-theme

assets/404.css
sections/404.liquid
templates/404.json

This PR's goal is to add 404 page to the theme

404 page implementation

---

assets/cart.css
sections/cart.liquid
sections/title.liquid
snippets/root-styles.liquid
snippets/variables-cart-lines.liquid
snippets/variables-cart-services.liquid
snippets/variables-cart-totals.liquid
templates/cart.json

The purpose of this PR is to implement the Cart page

Cart page implementation

---

assets/base.css
assets/contact-form.css
assets/form.css
sections/about-us.liquid
sections/articles.liquid
sections/call-to-action.liquid
sections/collection-page.liquid
sections/collections.liquid
sections/columns.liquid
sections/contact-form.liquid
sections/footer.liquid
sections/header.liquid
sections/hero.liquid
sections/logos.liquid
sections/products.liquid
sections/search.liquid
sections/testimonials.liquid
sections/title.liquid
sections/top-bar.liquid
snippets/form.liquid
snippets/socials.liquid
templates/page.contact.json

The goal of this PR is to implement the Contact page

Contact page

---

assets/account.css
assets/base.css
layout/session.liquid
sections/accept-invitation.liquid
sections/activate-account.liquid
sections/edit-password-form.liquid
sections/login-form.liquid
sections/register-form.liquid
sections/reset-password-form.liquid
snippets/form-password-session-pages.liquid
snippets/form.liquid
snippets/root-styles.liquid
snippets/variables-mini-cart.liquid
templates/accept-invitation.json
templates/activate-account.json
templates/edit-password.json
templates/login.json
templates/register.json
templates/reset-password.json

This PR's goal is to integrate session pages into theme

Session pages integration

---

layout/checkout.liquid
layout/theme.liquid
snippets/page-metadata.liquid

This PR aims to add a checkout layout to the theme.
Also, metadata should be added to layouts if they were skipped

Add checkout layout and  metadata

---

assets/header.js
assets/menu.css
assets/product-card.css
config/settings_data.json
sections/collection-page.liquid
sections/products.liquid
sections/search.liquid
snippets/product-card.liquid

Currently, the menu peeks out from under the header in Preview mode
So this PR's purpose is to fix the menu positioning and slightly clean up the code
**Before:**
**After:**

Fix positioning menu in Preview mode

---

assets/adore/search-form.css
assets/base.css
assets/search-form.css
assets/top-bar.css
config/settings_data.json

The purpose of this PR is to fix some UI issues in the Header after the first QA round

Fix the Header UI issues

---

assets/adore/header.css
assets/adore/menu.css
assets/adore/secondary-menu.js
config/settings_schema.json
sections/adore/header.liquid
sections/title.liquid
snippets/root-styles.liquid
templates/bliss/page.json
templates/bliss/search.json
templates/page.json
templates/search.json

This PR's goal is to fix an issue with the secondary menu that causes the dropdown to close prematurely.
The menu can be hard to navigate as it collapses while moving the cursor from base level to level 1.
So it is supposed to be added delay time in the menu to avoid the dropdown collapsing
Before:
After:

Mega menu UX improvements

---

assets/cookie-notice-preferences.css
assets/text.css
config/settings_schema.json
layout/theme.liquid
sections/cookie-notice-preferences.liquid
sections/text.liquid
snippets/root-styles.liquid
templates/privacy-policy.json

The purpose of this PR is to implement cookie notice

Cookie notice implementation

---

assets/cookie-notice-preferences.css
sections/cookie-notice-preferences.liquid
templates/privacy-policy.json

This PR's goal is to add missed styles and settings for the cookie notice section

Update cookie notice section styles and settings

---

assets/404.css
assets/adore/header.css
assets/adore/quick-menu.css
assets/base.css
sections/cookie-notice-preferences.liquid
templates/bliss/page.json
templates/page.json

This PR's purpose is to fix the blank space between the last section and the footer on big screens
Before:
After:

Fix blank space between the last section and footer

---

assets/base.css

[Initial issue](https://github.com/booqable/impact-theme/pull/106)

Fix the border-radius of locations in a new date picker

---

config/meta.json

I've got a change request from Nathan to replace the industry value of the Care variation from `Medical` to `Medical / Healthcare`

Update market value for the `Care` variation

---

assets/404.css
assets/base.css
assets/footer.css
assets/product-card.css
assets/product-page.css
assets/rx.css
assets/sidebar.css
snippets/variables-cart-totals.liquid
snippets/variables-product-quantity.liquid

The feature of changing font weights of headings was implemented earlier but now some styles should be corrected

Adjust styles of font weights of headings

---

assets/image-gallery.css
sections/image-gallery.liquid

There is a new element that we would like in Horton themes. It's an image gallery people can use to share images on their website

Add a new Image gallery section

---

assets/footer.css
snippets/product-card.liquid

This PR's goal is to add nowrap style to the footer's Weglot app dropdown to improve the inside layout
Before:
After:

Improve the footer Weglot

---

assets/sidebar.css
assets/sidebar.js
layout/theme.liquid
snippets/root-styles.liquid
snippets/sidebar.liquid

Initial PR https://github.com/booqable/chameleon-theme/pull/254

Add automatic fade out effect with js for sidebar dropdown if it's taller than parent element

---

sections/product-page.liquid
templates/bliss/product.json
templates/product.json

Initial issue https://github.com/booqable/chameleon-theme/pull/255

Add the product description placement option for the product page

---

sections/title.liquid
templates/bliss/cart.json
templates/bliss/collection.json
templates/bliss/page.json
templates/cart.json
templates/collection.json
templates/page.json

Initial issue https://github.com/booqable/chameleon-theme/pull/256

Supporting dynamic titles and descriptions from page context

---

assets/product-page.css

Initial issue https://github.com/booqable/chameleon-theme/pull/257

Add padding for product description

---

assets/rx.css

Initial issue https://github.com/booqable/chameleon-theme/pull/258

Refactor font weights of WYSIWYG elements

---

sections/image-gallery.liquid

Part of https://linear.app/booqable/issue/GUA-1318/add-liquid-strict-mode-feature-flag-for-better-template-error

Fixes modulo operation on image gallery

---

sections/product-page.liquid
templates/bliss/product.json
templates/product.json

[Initial issue](https://github.com/booqable/chameleon-theme/pull/332)

Clean up the `Variation label`
