assets/adore/app.css, assets/adore/header.css, assets/adore/menu.css, assets/adore/search-form.css, assets/adore/support.css, assets/app.css, assets/header.css, assets/search-form.css, assets/search.js, config/settings_data.json, sections/adore/header.liquid, sections/header.liquid, snippets/mega-menu.liquid, snippets/search-form.liquid
This PR's goal is to implement a new header for the Adore variant of theme
Some elements are reused in both headers so they were separated into the snippets
Before:
After:
=> New header for Adore variant

config/settings_data.json, sections/adore/header.liquid, sections/articles.liquid, sections/columns.liquid, templates/adore/index.json, templates/bliss/index.json, templates/spring/index.json
This PR supposed to fix previews of blocks in theme editor if it's show wrong information or information missed at all.
Before:
After:
=> Fix issue when previews of blocks show wrong information or missed at all

assets/testimonials.css
This PR's goal is to fix the positioning of quotation marks in testimonials section
Before:
After:
=> Fix positioning of testimonial quotation marks

assets/cookie-notice-preferences.css, assets/search-form.css, sections/cookie-notice-preferences.liquid, templates/privacy-policy.json
The search bar looks disabled in the Bliss and Spring variants.
So this PR's purpose is to make the white background
Before:
After:
=> Change the color of search input field to white

assets/top-bar.css
The customer complained that after he changed the content on the Top bar, then it looked broken, so this PR aims to fix the issue
Before:
After:
=> Add center alignment for top bar info items

sections/hero.liquid
After deploying the latest changes to production I noticed that content in the Hero section had become broken on the customer's site because the max-width content option has been automatically applied there. Therefore, the default value `true` of `full_width_content` should fix the issue
=> Update the default value to true for full-width content in the Hero section

assets/hero.css, sections/hero.liquid, templates/achieve/index.json, templates/adore/index.json, templates/bliss/index.json, templates/breeze/index.json, templates/care/index.json, templates/create/index.json, templates/crisp/index.json, templates/moment/index.json, templates/motion/index.json, templates/navigate/index.json, templates/place/index.json, templates/raw/index.json, templates/route/index.json, templates/scenic/index.json, templates/shine/index.json, templates/signature/index.json, templates/space/index.json, templates/spring/index.json
Once we had been implementing this feature but after deploying it on production there were some complaints of broken layouts in section, therefore everything was reverted. 
Now we don't use any restrictions for the Hero section's content and still it can be a bit confusing for customers to have to add line breaks to get the look they want (aligned to the left or right side of the screen).
So all previous issues were taken into account and this PR aims to add an extra max-width option to limit the width of Hero section's content as in designs
=> Add limit content by width option in Hero section

assets/text-with-image.css, sections/text-with-image.liquid
We would like to add a component to be available in the Horton themes that looks like this
This will allow us to make more varied pages in the previews for pages like "About us" and 'How it works" as well as giving customers more options
=> Add the new `Text with image` section

config/settings_data.json, config/settings_schema.json, snippets/product-card.liquid
We started getting complaints from customers as expected. They said that they didn't change anything, but the colors such as highlights, text color, backgrounds have been changed on their webshop. 
It happened because yesterday we released a separate color scheme for product cards and set the default value to `color set 1` which is not suitable for some customers obviously.
So this PR aims to add a new `use color scheme` option and set its value to `false` so that colors can't affect customers' initial colors without forced enabling
=> Add `use color scheme` option to Product card settings

assets/adore/menu.css, assets/adore/quick-menu.css, assets/adore/search-form.css, assets/base.css, assets/create/menu.css, assets/create/quick-menu.css, assets/create/search-form.css, assets/menu.css, assets/moment/menu.css, assets/moment/quick-menu.css, assets/moment/search-form.css, assets/navigate/menu.css, assets/navigate/quick-menu.css, assets/navigate/search-form.css, assets/search-form.css, assets/shine/menu.css, assets/shine/quick-menu.css, assets/shine/search-form.css, assets/space/menu.css, assets/space/quick-menu.css, assets/space/search-form.css, assets/touch-device-notch.js
This PR is dedicated to enhance device detection and styles for mobile device compatibility
Also, after testing the Horton theme on various mobile devices and browsers in BrowserStack there are issues need to be fixed:
1. The `search bar` in the header is overlaped with the menu button on iPad in landscape device orientation
2. Position of the `search bar` and `quick menu` for theme variations that have custom header on iPhone in landscape device orientation
Before:
After:
=> Fix bug of overlapping the search bar on iPad in landscape

assets/product-page.css, sections/product-page.liquid
The customer reported that the Horton theme doesn't show the rental period on the product page.
Therefore, this PR's purpose is to implement the rental period next to the price
Before:
After:
=> Add the missing rental period to the product page

assets/adore/menu.css, assets/create/menu.css, assets/menu.css, assets/menu.js, assets/moment/menu.css, assets/navigate/menu.css, assets/shine/menu.css, assets/space/menu.css
The purpose of this PR is to fix non-scrollable dropdown menu if there are a lot of items extending beyond the screen
Before:
After:
=> Fix non-scrollable long menu dropdown on small screens

assets/rx.css
Initial [issue](https://github.com/booqable/impact-theme/pull/120)
=> Add margin-bottom reset for the last heading elements in WYSIWYG editor

assets/adore/menu.css, assets/create/menu.css, assets/menu.css, assets/moment/menu.css, assets/navigate/menu.css, assets/shine/menu.css, assets/space/menu.css
The customer complained that the mobile menu doesn't have a gap on the left side and text is stuck to the edge of the screen. This happened after reverting to the default page scrollbar styles.
So this PR aims to fix the dropdown width if the scrollbar is always visible
Before:
After:
=> Fix the left gap of the mobile menu

assets/title.css, sections/title.liquid
This PR aims to fix the Liquid error: internal in the Title section. I'm unsure why liquid `default` filter is not working anymore here. Maybe it happened because of changes in collections on the backend because it was working properly before. I figured it out because by removing the `default: collection.title` filter everything works fine and the problem only occurs on the homepage.
So the changes include making the CSS more robust with fallback values and simplifying the logic for handling titles and descriptions in the Liquid file.
* [`assets/title.css`](diffhunk://#diff-d479a1821c7e1f7b1579a85bb408fe0e174c5dd2a857677b145d0b240934a8ccL29-R29): Updated the `padding-bottom` property to include a fallback value (`50px`) in case the `--date-picker-extra-indent` variable is not defined. …
=> Fix `Liquid error: internal` in Title section

assets/menu.css
The customer complained that the dropdown menu is cut off on the left side. It happens when no words in the menu button  and the logo is small.
Therefore this PR includes a tiny change to the `menu.css` file. The change updates the `margin-left` property of `.header-sticky .menu__list` to use the `clamp()` function to avoid it getting a value below 0.
=> Fix cut off dropdown menu on desktop

sections/app.liquid
When users add an new App section but before they choose which app to put in the section that section will have no blocks, resulting in a blank space which is a bit disorienting. This change additionally renders the preview when the user hasn't picked an app block yet.
---
Before:
After:
=> Also render the preview if we don't have an app block yet

assets/adore/menu.css, assets/create/menu.css, assets/moment/menu.css, assets/navigate/menu.css, assets/shine/menu.css, assets/space/menu.css
The customer complained that text justification for the Secondary Menu has irregular text justification. Some elements are left, center, or right justified.
This PR introduces consistent updates across several themes having header with blocks to enhance menu styling and responsiveness. The changes include significant improvements to dropdown menus. These updates aim to provide a more uniform and user-friendly experience.
* Added `--menu-secondary-dropdown-padding-x` variable for consistent horizontal padding in dropdown menus. Set the width of dropdown items to have the same width across all dropdowns of the secondary menu. (`assets/adore/menu.css` [[1]](diffhunk://#diff-fc3990909a7bcdac2a16bbea9fad7c4d477335750923ef76c9718d6d53a41c7eR322-R338) `assets/create/menu.css` …
=> Align secondary menu dropdown items

sections/footer.liquid
On a fresh install of a Horton theme you can see a liquid error in the bottom. It seems to come from this default value where `"` is escaped with a slash. That does not seem to work, so I changed the double quote to a single quote and this seems to work well.
Resolves [SC-1718](https://linear.app/booqable/issue/SC-1718/horton-theme-footer-has-syntax-issues)
=> Footer: Fix liquid syntax error in default installation

assets/articles.css
This PR updates the styling of article components to fix display issues on iPhone 11.
Changes were tested on a real device iPhone 11 pro max iOS 16.5
=> Fix flattened articles on iPhone 11

sections/adore/header.liquid, sections/create/header.liquid, sections/header.liquid, sections/moment/header.liquid, sections/navigate/header.liquid, sections/shine/header.liquid, sections/space/header.liquid
This PR makes a small but important fix to the way the logo image is rendered in multiple header section files. The change ensures that the correct parameter name, `image_alt`, is used instead of the incorrect `image__alt`, which improves consistency and prevents potential issues with image alt text rendering.
=> Fix typo in image `alt` key

snippets/collections-grid.liquid
This PR aims to improve the accessibility and context of collection images by providing more descriptive alternative text. The main focus is on ensuring that the image `alt` attribute is set dynamically based on the displayed image in each collection. [Initial PR](https://github.com/booqable/chameleon-theme/pull/343)
=> Update `alt` attribute assignment for collection images
